### ISSUE TITLE
sdist doesnt include normal  top level directory

### ISSUE THREAD

**Issue by jayvdb** [dephell/dephell_specifier#1]
The sdist should only contain `dephell_specifier-x.y.z/` ; instead the top level contains the files and directories normally found in  `dephell_specifier-x.y.z/`

**Comment by jayvdb** [comment]
This appears to effect all of the dephell packages.  This makes them very difficult to work with in rpmbuild, as I need to manually create the extra dir.  Bit ironic that a tool to manage packages doesnt have usable sdists.

Also they do not have LICENSE files in their sdist.

And the few I have looked at also dont have tests included in the sdist.

**Comment by jayvdb** [comment]
The rpm .spec for almost every other python package looks like

```spec
%prep
%setup -q -n dephell_specifier-%{version}

%build
%python_build

%install
%python_install
```

For dephell, it needs to be like

```spec
%prep
# https://github.com/dephell/dephell_specifier/issues/1
# can not use
# %%setup -q -n dephell_specifier-%{version}
mkdir dephell_specifier-%{version}
cd dephell_specifier-%{version}
tar -xzf %{SOURCE0}

%build
cd dephell_specifier-%{version}
%python_build

%install
cd dephell_specifier-%{version}
%python_install
```

**Comment by orsinium** [comment]
Thank you for issue. Please, provide an example of sdist tree in good package and bad package. I didn't catch the point.

> Bit ironic that a tool to manage packages doesnt have usable sdists.

All dephell packages builded by dephell. All build algorithms implemented by me and tested only with pip and setuptools. Of course, there can be troubles. This is the only reason why dephell has version <1.0.0. I can't cover all cases by myself. So, I happy to fix issues like this :)

**Comment by orsinium** [comment]
Oh, I got it. I will fix it, thank you :)

**Comment by jayvdb** [comment]
Great.  I'll be happy to retest building RPMs.  e.g. if you want to only do a new sdist of only one dephell-foo-package first, even pre-release or devpi release, I can grab the tarball and retry running the rpm build to confirm the main problem is fixed, and let you know of ways it can be improved.  dephell-specifier is a good one, as it has no other dephell dependencies.

A good way to ensure the sdist tarball is complete is to compare it with what `check-manifest` (on pypi) would do with `MANIFEST.in`.

**Comment by orsinium** [comment]
Please, check this sdist:
https://github.com/dephell/dephell_specifier/releases/download/v.0.1.5/dephell_specifier-0.1.5.tar.gz

**Comment by jayvdb** [comment]
https://build.opensuse.org/package/show/home:jayvdb:dephell/python-dephell-specifier looks quite good, however it is missing the tests.  I've put more detail about the tests in a new issue at https://github.com/dephell/dephell/issues/95

**Comment by orsinium** [comment]
I've reuploaded all packages in dephell ecosystem. Thank you for issue :)
