### ISSUE TITLE
PyPI metadata is empty

### ISSUE THREAD

**Issue by jayvdb** [dephell/dephell_specifier#13]
https://pypi.org/project/dephell-specifier/ doesnt have homepage or other metadata as it hasnt been updated since support for that was added to dephell.

If you dont have any better ideas for what to include in a new release, I can do a README update to describe all of the possible types of specifiers (which you added for me), if that is sufficient to justify a new release.

**Comment by orsinium** [comment]
Thank you! I'll fix it.
