### ISSUE TITLE
Support for various comparitors and range syntax

### ISSUE THREAD

**Issue by jayvdb** [dephell/dephell_specifier#3]
I noticed that this library has support for npm's range syntax.

Is the intention to support any sufficiently prominent syntax?

E.g. `RangeSpecifier("~>2.1.1")` fails.  This is [Ruby's pessimistic operator](https://thoughtbot.com/blog/rubys-pessimistic-operator), used in Gemfile syntax, and also used by [D](https://dub.pm/package-format-json).

Another one is `(,1.0]` and similar used by [Maven](https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#CJHDEHAB) and [Ivy](https://ant.apache.org/ivy/history/2.1.0/settings/version-matchers.html) (and most of the Java world), and also ["Visual Studio" (and many many friends)](https://docs.microsoft.com/en-us/nuget/reference/package-versioning)

**Comment by orsinium** [comment]
Library supports npm's syntax to be compatible with poetry. So, it's already in Python packaging. Unfortunately

**Comment by orsinium** [comment]
For intervals:
https://pypi.org/project/python-intervals/

**Comment by jayvdb** [comment]
Is maintaining compatibility with poetry the ~~old~~ primary goal of dephell?

That will make https://github.com/dephell/dephell/issues/98 somewhat constrained, as rpm definitely has a different versioning scheme most notice-able after the hyphen, and deb does too iirc, and I'd put money on msi putting a spanner in the wheel too.

**Comment by jayvdb** [comment]
> For intervals:
> https://pypi.org/project/python-intervals

I didnt understand what you meant by this.  That package doesnt seem to be a dependency of dephell, at least not directly.

**Comment by orsinium** [comment]
I thought you're looking for a library to parse specifiers in your custom project, not in DepHell. DepHell doesn't support range syntax because can't read maven/ivy dependency files.

**Comment by jayvdb** [comment]
Ah, I see why you mentioned that.

Actually I dont have much interest in maven/ivy/vs version specifiers, at least not at the moment.

Gemfile version specs is what I am working on atm.  I am looking for where to contribute python code for that, where people are interested in version specs and dependency file formats that are used outside of the Python world.  I worked-around the py34 problem by [vendoring dephell_specifier](https://gitlab.com/jayvdb/package_manager/commit/1ab4d34a), so `dephell_specifier` and `semantic_version` appear to be the two best alternatives for @coala needs.

Before dephell could read other dependency file formats, it needs to be able to parse the versions and specifiers in them, otherwise parsing the file is not helpful for dephell.  Hence I thought that maybe this project would be interested in solutions to the lowest layer of the problem - parsing non-Python-compatible versions, and there is already support for npm at https://github.com/dephell/dephell_specifier/blob/80847b9/dephell_specifier/range_specifier.py#L65  

So if you are interested in Ruby/D support, I will add `~>` support shortly.  Maven/Ivy version specs would take a bit longer.
Otherwise, close this issue as out of scope and I'll be on my way.
