### ISSUE TITLE
Retrieving input out of Specifier('==1.0-1')

### ISSUE THREAD

**Issue by jayvdb** [dephell/dephell_specifier#4]
`str(Specifier('==1.0-1'))` is `==1.0-1` however 

`str(Specifier('==1.0-1').version)` is `1.0.post1`

To get `1.0-1` back out, I need to do `str(Specifier('==1.0-1')._spec.version)`

`1.0-1` is `1.0.post1` in equivalent in recent versions of Python libraries, but doesnt hold true in other packaging version systems.

I may be trying to use @dephell out of its intended scope, going a bit further even than https://github.com/dephell/dephell/issues/98 .  c.f. https://github.com/dephell/dephell_specifier/issues/3

I am hoping to use dephell for https://gitlab.com/coala/package_manager , specifically https://gitlab.com/coala/package_manager/issues/6 .  We support a rather large list of package managers ; c.f. https://gitlab.com/coala/package_manager/tree/master/dependency_management/requirements , but have not parsed the `version` field passed to our classes, until now.  It has been approximately a specifier, but also held discrete versions.  That is easy enough to handle using `dephell_specifier`.

With a few exceptions (fixable with https://github.com/dephell/dephell_specifier/issues/3), dephell_specifier seems to be quite suitable.

Except I need to be able to get the version back out, without Python-specific rewriting of the version string (i.e. the `-1' -> `.post`` transform), and ideally avoiding `_` underscore prefixed values.

Perhaps adding a property `raw_version` that returns `self._spec.version` ?

**Comment by jayvdb** [comment]
And then I see this library for versions isnt usable on Python 3.4, so I cant use it.

**Comment by orsinium** [comment]
End of life for 3.4 was in March of this year :(
