### ISSUE TITLE
AttributeError: 'Version' object has no attribute 'release'

### ISSUE THREAD

**Issue by jayvdb** [dephell/dephell_specifier#9]
Quick headsup as I am fairly confident this isnt a problem with my code.  Possibly a problem with my `packaging` version

```py
constr = '~>0.4.0'

    @staticmethod
    def _parse_npm(constr: str) -> Set[Specifier]:
        version = parse(constr.lstrip('~^=>').replace('.*', '.0'))
        if isinstance(version, LegacyVersion):
            raise InvalidSpecifier(constr)
>       parts = version.release + (0, 0)
E       AttributeError: 'Version' object has no attribute 'release'
```
```
> python3 -c 'import packaging; print(packaging.__version__)'
19.0
```

**Comment by jayvdb** [comment]
Or maybe its the extra commits since I vendored - I'm pulling and retesting again.

**Comment by orsinium** [comment]
:scream:

**Comment by orsinium** [comment]
Could you run tests, please? Do they reproduce it, or I need to write new one?

**Comment by orsinium** [comment]
https://github.com/pypa/packaging/blob/master/packaging/version.py#L281
:thinking:

**Comment by orsinium** [comment]
Ok, let's update library for the beginning. Please, update `dephell_specifier` to `0.2.0`. I've released it a few seconds before your issue.

**Comment by jayvdb** [comment]
I have a job running with my tests -- it will be 10 mins before I get results.

I'm also trying to bisect.

`PYTHONPATH=. python3 -c 'from dephell_specifier.range_specifier import RangeSpecifier; RangeSpecifier("~>0.4.0")'` is what I suspect was failing, for one of the commits.

**Comment by jayvdb** [comment]
Actually likely this is caused by packaging-16.8 . I can increase my pinned version, just need to find which version is needed.

**Comment by jayvdb** [comment]
Needs packaging 17.1 I think.

**Comment by jayvdb** [comment]
Yup; that was it.
Apologies if packaging 16.8 isnt possible except because of my vendoring.

fwiw, I've also been noticing an error on travis that has baffled me a bit
```
$ curl https://raw.githubusercontent.com/dephell/dephell/master/install.py | /opt/python/3.6/bin/python
/home/travis/.travis/functions: line 104: /opt/python/3.6/bin/python: No such file or directory
(23) Failed writing body
The command "curl https://raw.githubusercontent.com/dephell/dephell/master/install.py | /opt/python/3.6/bin/python" failed and exited with 127 during .
```

https://travis-ci.org/jayvdb/dephell_specifier/jobs/555382165

**Comment by orsinium** [comment]
Looks like network error on travis, try to restart the job

**Comment by jayvdb** [comment]
I've restarted the job a few times.

**Comment by orsinium** [comment]
Oh, I see. Use `3.6.7` instead `3.6` like in DepHell's ttavis.yml

**Comment by cmj18** [comment]
Hey guys,have you solved this question? I meet the same problem.

**Comment by jayvdb** [comment]
https://github.com/dephell/dephell is archived.

**Comment by cmj18** [comment]
> https://github.com/dephell/dephell is archived.

Awesome！

**Comment by orsinium** [comment]
i don't remember a thing about this issue, but didn't we solve it in #10?
